In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
PROCESSED_DIR = Path("../data/processed")

print("Processed data directory:")
print(PROCESSED_DIR.resolve())

Processed data directory:
C:\Users\sukhy\Desktop\smart-energy-project\data\processed

In [3]:
regions = [
    "AEP",
    "COMED",
    "DAYTON",
    "DEOK",
    "DOM",
    "DUQ",
    "EKPC",
    "FE",
    "NI",
    "PJME",
    "PJMW"
]

data = {}

for region in regions:
    file_path = PROCESSED_DIR / f"{region}_cleaned.csv"
    
    df = pd.read_csv(file_path)
    df["Datetime"] = pd.to_datetime(df["Datetime"])
    
    data[region] = df

print(f"Loaded {len(data)} regional datasets.")

Loaded 11 regional datasets.

In [4]:
feature_data = {}

for region, df in data.items():
    
    df = df.copy()
    
    df["hour"] = df["Datetime"].dt.hour
    df["day"] = df["Datetime"].dt.day
    df["day_of_week"] = df["Datetime"].dt.dayofweek
    df["month"] = df["Datetime"].dt.month
    df["year"] = df["Datetime"].dt.year
    
    df["is_weekend"] = (
        df["day_of_week"] >= 5
    ).astype(int)
    
    feature_data[region] = df

print("Time-based features created.")

Time-based features created.

In [5]:
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"

In [6]:
for region, df in feature_data.items():
    df["season"] = df["month"].apply(get_season)

In [7]:
for region, df in feature_data.items():
    
    energy_col = df.columns[1]
    
    df["lag_1"] = df[energy_col].shift(1)
    df["lag_2"] = df[energy_col].shift(2)
    df["lag_3"] = df[energy_col].shift(3)
    
    df["lag_24"] = df[energy_col].shift(24)
    df["lag_48"] = df[energy_col].shift(48)
    
    df["lag_168"] = df[energy_col].shift(168)

In [8]:
for region, df in feature_data.items():
    
    energy_col = df.columns[1]
    
    df["rolling_mean_24"] = (
        df[energy_col]
        .shift(1)
        .rolling(24)
        .mean()
    )
    
    df["rolling_std_24"] = (
        df[energy_col]
        .shift(1)
        .rolling(24)
        .std()
    )
    
    df["rolling_mean_168"] = (
        df[energy_col]
        .shift(1)
        .rolling(168)
        .mean()
    )

In [9]:
feature_data["PJME"].head(30)

,Datetime,PJME_MW,hour,day,day_of_week,month,year,is_weekend,season,lag_1,lag_2,lag_3,lag_24,lag_48,lag_168,rolling_mean_24,rolling_std_24,rolling_mean_168
0,2002-01-01 01:00:00,30393.0,1,1,1,1,2002,0,Winter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2002-01-01 02:00:00,29265.0,2,1,1,1,2002,0,Winter,30393.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2002-01-01 03:00:00,28357.0,3,1,1,1,2002,0,Winter,29265.0,30393.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2002-01-01 04:00:00,27899.0,4,1,1,1,2002,0,Winter,28357.0,29265.0,30393.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2002-01-01 05:00:00,28057.0,5,1,1,1,2002,0,Winter,27899.0,28357.0,29265.0,NaN,NaN,NaN,NaN,NaN,NaN
5,2002-01-01 06:00:00,28654.0,6,1,1,1,2002,0,Winter,28057.0,27899.0,28357.0,NaN,NaN,NaN,NaN,NaN,NaN
6,2002-01-01 07:00:00,29308.0,7,1,1,1,2002,0,Winter,28654.0,28057.0,27899.0,NaN,NaN,NaN,NaN,NaN,NaN
7,2002-01-01 08:00:00,29595.0,8,1,1,1,2002,0,Winter,29308.0,28654.0,28057.0,NaN,NaN,NaN,NaN,NaN,NaN
8,2002-01-01 09:00:00,29943.0,9,1,1,1,2002,0,Winter,29595.0,29308.0,28654.0,NaN,NaN,NaN,NaN,NaN,NaN
9,2002-01-01 10:00:00,30692.0,10,1,1,1,2002,0,Winter,29943.0,29595.0,29308.0,NaN,NaN,NaN,NaN,NaN,NaN
10,2002-01-01 11:00:00,31395.0,11,1,1,1,2002,0,Winter,30692.0,29943.0,29595.0,NaN,NaN,NaN,NaN,NaN,NaN
11,2002-01-01 12:00:00,31496.0,12,1,1,1,2002,0,Winter,31395.0,30692.0,29943.0,NaN,NaN,NaN,NaN,NaN,NaN
12,2002-01-01 13:00:00,31031.0,13,1,1,1,2002,0,Winter,31496.0,31395.0,30692.0,NaN,NaN,NaN,NaN,NaN,NaN
13,2002-01-01 14:00:00,30360.0,14,1,1,1,2002,0,Winter,31031.0,31496.0,31395.0,NaN,NaN,NaN,NaN,NaN,NaN
14,2002-01-01 15:00:00,29798.0,15,1,1,1,2002,0,Winter,30360.0,31031.0,31496.0,NaN,NaN,NaN,NaN,NaN,NaN
15,2002-01-01 16:00:00,29720.0,16,1,1,1,2002,0,Winter,29798.0,30360.0,31031.0,NaN,NaN,NaN,NaN,NaN,NaN
16,2002-01-01 17:00:00,31271.0,17,1,1,1,2002,0,Winter,29720.0,29798.0,30360.0,NaN,NaN,NaN,NaN,NaN,NaN
17,2002-01-01 18:00:00,35103.0,18,1,1,1,2002,0,Winter,31271.0,29720.0,29798.0,NaN,NaN,NaN,NaN,NaN,NaN
18,2002-01-01 19:00:00,35732.0,19,1,1,1,2002,0,Winter,35103.0,31271.0,29720.0,NaN,NaN,NaN,NaN,NaN,NaN
19,2002-01-01 20:00:00,35639.0,20,1,1,1,2002,0,Winter,35732.0,35103.0,31271.0,NaN,NaN,NaN,NaN,NaN,NaN
20,2002-01-01 21:00:00,35285.0,21,1,1,1,2002,0,Winter,35639.0,35732.0,35103.0,NaN,NaN,NaN,NaN,NaN,NaN
21,2002-01-01 22:00:00,34007.0,22,1,1,1,2002,0,Winter,35285.0,35639.0,35732.0,NaN,NaN,NaN,NaN,NaN,NaN
22,2002-01-01 23:00:00,31857.0,23,1,1,1,2002,0,Winter,34007.0,35285.0,35639.0,NaN,NaN,NaN,NaN,NaN,NaN
23,2002-01-02 00:00:00,29563.0,0,2,2,1,2002,0,Winter,31857.0,34007.0,35285.0,NaN,NaN,NaN,NaN,NaN,NaN
24,2002-01-02 01:00:00,28121.0,1,2,2,1,2002,0,Winter,29563.0,31857.0,34007.0,30393.0,NaN,NaN,31017.500000,2423.666231,NaN
25,2002-01-02 02:00:00,27437.0,2,2,2,1,2002,0,Winter,28121.0,29563.0,31857.0,29265.0,NaN,NaN,30922.833333,2492.512817,NaN
26,2002-01-02 03:00:00,27301.0,3,2,2,1,2002,0,Winter,27437.0,28121.0,29563.0,28357.0,NaN,NaN,30846.666667,2572.037370,NaN
27,2002-01-02 04:00:00,27533.0,4,2,2,1,2002,0,Winter,27301.0,27437.0,28121.0,27899.0,NaN,NaN,30802.666667,2624.967920,NaN
28,2002-01-02 05:00:00,28405.0,5,2,2,1,2002,0,Winter,27533.0,27301.0,27437.0,28057.0,NaN,NaN,30787.416667,2643.567746,NaN
29,2002-01-02 06:00:00,30748.0,6,2,2,1,2002,0,Winter,28405.0,27533.0,27301.0,28654.0,NaN,NaN,30801.916667,2628.853675,NaN

In [10]:
import pandas as pd
import numpy as np
from pathlib import Path

PROCESSED_DIR = Path("../data/processed")

regions = [
    "AEP", "COMED", "DAYTON", "DEOK", "DOM",
    "DUQ", "EKPC", "FE", "NI", "PJME", "PJMW"
]

data = {}

for region in regions:
    path = PROCESSED_DIR / f"{region}_cleaned.csv"
    df = pd.read_csv(path)
    df["Datetime"] = pd.to_datetime(df["Datetime"])
    data[region] = df

print(f"Loaded {len(data)} regions")

Loaded 11 regions

In [11]:
feature_data = {}

for region, df in data.items():
    df = df.copy()

    df["hour"] = df["Datetime"].dt.hour
    df["day"] = df["Datetime"].dt.day
    df["day_of_week"] = df["Datetime"].dt.dayofweek
    df["month"] = df["Datetime"].dt.month
    df["year"] = df["Datetime"].dt.year

    df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

    feature_data[region] = df

print("Time features created.")

Time features created.

In [12]:
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"


for region, df in feature_data.items():
    df["season"] = df["month"].apply(get_season)

In [13]:
for region, df in feature_data.items():

    energy_col = df.columns[1]

    df["lag_1"] = df[energy_col].shift(1)
    df["lag_2"] = df[energy_col].shift(2)
    df["lag_3"] = df[energy_col].shift(3)

    df["lag_24"] = df[energy_col].shift(24)
    df["lag_48"] = df[energy_col].shift(48)

    df["lag_168"] = df[energy_col].shift(168)

In [15]:
for region, df in feature_data.items():

    energy_col = df.columns[1]

    df["rolling_mean_24"] = (
        df[energy_col]
        .shift(1)
        .rolling(24)
        .mean()
    )

    df["rolling_std_24"] = (
        df[energy_col]
        .shift(1)
        .rolling(24)
        .std()
    )

    df["rolling_mean_168"] = (
        df[energy_col]
        .shift(1)
        .rolling(168)
        .mean()
    )

In [16]:
feature_data["PJME"].head(30)

,Datetime,PJME_MW,hour,day,day_of_week,month,year,is_weekend,season,lag_1,lag_2,lag_3,lag_24,lag_48,lag_168,rolling_mean_24,rolling_std_24,rolling_mean_168
0,2002-01-01 01:00:00,30393.0,1,1,1,1,2002,0,Winter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2002-01-01 02:00:00,29265.0,2,1,1,1,2002,0,Winter,30393.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2002-01-01 03:00:00,28357.0,3,1,1,1,2002,0,Winter,29265.0,30393.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2002-01-01 04:00:00,27899.0,4,1,1,1,2002,0,Winter,28357.0,29265.0,30393.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2002-01-01 05:00:00,28057.0,5,1,1,1,2002,0,Winter,27899.0,28357.0,29265.0,NaN,NaN,NaN,NaN,NaN,NaN
5,2002-01-01 06:00:00,28654.0,6,1,1,1,2002,0,Winter,28057.0,27899.0,28357.0,NaN,NaN,NaN,NaN,NaN,NaN
6,2002-01-01 07:00:00,29308.0,7,1,1,1,2002,0,Winter,28654.0,28057.0,27899.0,NaN,NaN,NaN,NaN,NaN,NaN
7,2002-01-01 08:00:00,29595.0,8,1,1,1,2002,0,Winter,29308.0,28654.0,28057.0,NaN,NaN,NaN,NaN,NaN,NaN
8,2002-01-01 09:00:00,29943.0,9,1,1,1,2002,0,Winter,29595.0,29308.0,28654.0,NaN,NaN,NaN,NaN,NaN,NaN
9,2002-01-01 10:00:00,30692.0,10,1,1,1,2002,0,Winter,29943.0,29595.0,29308.0,NaN,NaN,NaN,NaN,NaN,NaN
10,2002-01-01 11:00:00,31395.0,11,1,1,1,2002,0,Winter,30692.0,29943.0,29595.0,NaN,NaN,NaN,NaN,NaN,NaN
11,2002-01-01 12:00:00,31496.0,12,1,1,1,2002,0,Winter,31395.0,30692.0,29943.0,NaN,NaN,NaN,NaN,NaN,NaN
12,2002-01-01 13:00:00,31031.0,13,1,1,1,2002,0,Winter,31496.0,31395.0,30692.0,NaN,NaN,NaN,NaN,NaN,NaN
13,2002-01-01 14:00:00,30360.0,14,1,1,1,2002,0,Winter,31031.0,31496.0,31395.0,NaN,NaN,NaN,NaN,NaN,NaN
14,2002-01-01 15:00:00,29798.0,15,1,1,1,2002,0,Winter,30360.0,31031.0,31496.0,NaN,NaN,NaN,NaN,NaN,NaN
15,2002-01-01 16:00:00,29720.0,16,1,1,1,2002,0,Winter,29798.0,30360.0,31031.0,NaN,NaN,NaN,NaN,NaN,NaN
16,2002-01-01 17:00:00,31271.0,17,1,1,1,2002,0,Winter,29720.0,29798.0,30360.0,NaN,NaN,NaN,NaN,NaN,NaN
17,2002-01-01 18:00:00,35103.0,18,1,1,1,2002,0,Winter,31271.0,29720.0,29798.0,NaN,NaN,NaN,NaN,NaN,NaN
18,2002-01-01 19:00:00,35732.0,19,1,1,1,2002,0,Winter,35103.0,31271.0,29720.0,NaN,NaN,NaN,NaN,NaN,NaN
19,2002-01-01 20:00:00,35639.0,20,1,1,1,2002,0,Winter,35732.0,35103.0,31271.0,NaN,NaN,NaN,NaN,NaN,NaN
20,2002-01-01 21:00:00,35285.0,21,1,1,1,2002,0,Winter,35639.0,35732.0,35103.0,NaN,NaN,NaN,NaN,NaN,NaN
21,2002-01-01 22:00:00,34007.0,22,1,1,1,2002,0,Winter,35285.0,35639.0,35732.0,NaN,NaN,NaN,NaN,NaN,NaN
22,2002-01-01 23:00:00,31857.0,23,1,1,1,2002,0,Winter,34007.0,35285.0,35639.0,NaN,NaN,NaN,NaN,NaN,NaN
23,2002-01-02 00:00:00,29563.0,0,2,2,1,2002,0,Winter,31857.0,34007.0,35285.0,NaN,NaN,NaN,NaN,NaN,NaN
24,2002-01-02 01:00:00,28121.0,1,2,2,1,2002,0,Winter,29563.0,31857.0,34007.0,30393.0,NaN,NaN,31017.500000,2423.666231,NaN
25,2002-01-02 02:00:00,27437.0,2,2,2,1,2002,0,Winter,28121.0,29563.0,31857.0,29265.0,NaN,NaN,30922.833333,2492.512817,NaN
26,2002-01-02 03:00:00,27301.0,3,2,2,1,2002,0,Winter,27437.0,28121.0,29563.0,28357.0,NaN,NaN,30846.666667,2572.037370,NaN
27,2002-01-02 04:00:00,27533.0,4,2,2,1,2002,0,Winter,27301.0,27437.0,28121.0,27899.0,NaN,NaN,30802.666667,2624.967920,NaN
28,2002-01-02 05:00:00,28405.0,5,2,2,1,2002,0,Winter,27533.0,27301.0,27437.0,28057.0,NaN,NaN,30787.416667,2643.567746,NaN
29,2002-01-02 06:00:00,30748.0,6,2,2,1,2002,0,Winter,28405.0,27533.0,27301.0,28654.0,NaN,NaN,30801.916667,2628.853675,NaN

In [19]:
for region, df in feature_data.items():
    print(
        region,
        "rows =", len(df),
        "columns =", len(df.columns)
    )

AEP rows = 121273 columns = 18
COMED rows = 66497 columns = 18
DAYTON rows = 121275 columns = 18
DEOK rows = 57739 columns = 18
DOM rows = 116189 columns = 18
DUQ rows = 119068 columns = 18
EKPC rows = 45334 columns = 18
FE rows = 62874 columns = 18
NI rows = 58450 columns = 18
PJME rows = 145366 columns = 18
PJMW rows = 143206 columns = 18

In [18]:
feature_data["PJME"].head(30)

,Datetime,PJME_MW,hour,day,day_of_week,month,year,is_weekend,season,lag_1,lag_2,lag_3,lag_24,lag_48,lag_168,rolling_mean_24,rolling_std_24,rolling_mean_168
0,2002-01-01 01:00:00,30393.0,1,1,1,1,2002,0,Winter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2002-01-01 02:00:00,29265.0,2,1,1,1,2002,0,Winter,30393.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2002-01-01 03:00:00,28357.0,3,1,1,1,2002,0,Winter,29265.0,30393.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2002-01-01 04:00:00,27899.0,4,1,1,1,2002,0,Winter,28357.0,29265.0,30393.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2002-01-01 05:00:00,28057.0,5,1,1,1,2002,0,Winter,27899.0,28357.0,29265.0,NaN,NaN,NaN,NaN,NaN,NaN
5,2002-01-01 06:00:00,28654.0,6,1,1,1,2002,0,Winter,28057.0,27899.0,28357.0,NaN,NaN,NaN,NaN,NaN,NaN
6,2002-01-01 07:00:00,29308.0,7,1,1,1,2002,0,Winter,28654.0,28057.0,27899.0,NaN,NaN,NaN,NaN,NaN,NaN
7,2002-01-01 08:00:00,29595.0,8,1,1,1,2002,0,Winter,29308.0,28654.0,28057.0,NaN,NaN,NaN,NaN,NaN,NaN
8,2002-01-01 09:00:00,29943.0,9,1,1,1,2002,0,Winter,29595.0,29308.0,28654.0,NaN,NaN,NaN,NaN,NaN,NaN
9,2002-01-01 10:00:00,30692.0,10,1,1,1,2002,0,Winter,29943.0,29595.0,29308.0,NaN,NaN,NaN,NaN,NaN,NaN
10,2002-01-01 11:00:00,31395.0,11,1,1,1,2002,0,Winter,30692.0,29943.0,29595.0,NaN,NaN,NaN,NaN,NaN,NaN
11,2002-01-01 12:00:00,31496.0,12,1,1,1,2002,0,Winter,31395.0,30692.0,29943.0,NaN,NaN,NaN,NaN,NaN,NaN
12,2002-01-01 13:00:00,31031.0,13,1,1,1,2002,0,Winter,31496.0,31395.0,30692.0,NaN,NaN,NaN,NaN,NaN,NaN
13,2002-01-01 14:00:00,30360.0,14,1,1,1,2002,0,Winter,31031.0,31496.0,31395.0,NaN,NaN,NaN,NaN,NaN,NaN
14,2002-01-01 15:00:00,29798.0,15,1,1,1,2002,0,Winter,30360.0,31031.0,31496.0,NaN,NaN,NaN,NaN,NaN,NaN
15,2002-01-01 16:00:00,29720.0,16,1,1,1,2002,0,Winter,29798.0,30360.0,31031.0,NaN,NaN,NaN,NaN,NaN,NaN
16,2002-01-01 17:00:00,31271.0,17,1,1,1,2002,0,Winter,29720.0,29798.0,30360.0,NaN,NaN,NaN,NaN,NaN,NaN
17,2002-01-01 18:00:00,35103.0,18,1,1,1,2002,0,Winter,31271.0,29720.0,29798.0,NaN,NaN,NaN,NaN,NaN,NaN
18,2002-01-01 19:00:00,35732.0,19,1,1,1,2002,0,Winter,35103.0,31271.0,29720.0,NaN,NaN,NaN,NaN,NaN,NaN
19,2002-01-01 20:00:00,35639.0,20,1,1,1,2002,0,Winter,35732.0,35103.0,31271.0,NaN,NaN,NaN,NaN,NaN,NaN
20,2002-01-01 21:00:00,35285.0,21,1,1,1,2002,0,Winter,35639.0,35732.0,35103.0,NaN,NaN,NaN,NaN,NaN,NaN
21,2002-01-01 22:00:00,34007.0,22,1,1,1,2002,0,Winter,35285.0,35639.0,35732.0,NaN,NaN,NaN,NaN,NaN,NaN
22,2002-01-01 23:00:00,31857.0,23,1,1,1,2002,0,Winter,34007.0,35285.0,35639.0,NaN,NaN,NaN,NaN,NaN,NaN
23,2002-01-02 00:00:00,29563.0,0,2,2,1,2002,0,Winter,31857.0,34007.0,35285.0,NaN,NaN,NaN,NaN,NaN,NaN
24,2002-01-02 01:00:00,28121.0,1,2,2,1,2002,0,Winter,29563.0,31857.0,34007.0,30393.0,NaN,NaN,31017.500000,2423.666231,NaN
25,2002-01-02 02:00:00,27437.0,2,2,2,1,2002,0,Winter,28121.0,29563.0,31857.0,29265.0,NaN,NaN,30922.833333,2492.512817,NaN
26,2002-01-02 03:00:00,27301.0,3,2,2,1,2002,0,Winter,27437.0,28121.0,29563.0,28357.0,NaN,NaN,30846.666667,2572.037370,NaN
27,2002-01-02 04:00:00,27533.0,4,2,2,1,2002,0,Winter,27301.0,27437.0,28121.0,27899.0,NaN,NaN,30802.666667,2624.967920,NaN
28,2002-01-02 05:00:00,28405.0,5,2,2,1,2002,0,Winter,27533.0,27301.0,27437.0,28057.0,NaN,NaN,30787.416667,2643.567746,NaN
29,2002-01-02 06:00:00,30748.0,6,2,2,1,2002,0,Winter,28405.0,27533.0,27301.0,28654.0,NaN,NaN,30801.916667,2628.853675,NaN

In [20]:
for region, df in feature_data.items():
    print(
        region,
        "NaN values:",
        df.isna().sum().sum()
    )

AEP NaN values: 462
COMED NaN values: 462
DAYTON NaN values: 462
DEOK NaN values: 462
DOM NaN values: 462
DUQ NaN values: 462
EKPC NaN values: 462
FE NaN values: 462
NI NaN values: 462
PJME NaN values: 462
PJMW NaN values: 462

In [21]:
for region, df in feature_data.items():
    feature_data[region] = (
        df.dropna()
          .reset_index(drop=True)
    )

print("Initial NaN rows removed.")

Initial NaN rows removed.

In [22]:
for region, df in feature_data.items():
    print(
        region,
        "rows =", len(df),
        "| NaNs =", df.isna().sum().sum()
    )

AEP rows = 121105 | NaNs = 0
COMED rows = 66329 | NaNs = 0
DAYTON rows = 121107 | NaNs = 0
DEOK rows = 57571 | NaNs = 0
DOM rows = 116021 | NaNs = 0
DUQ rows = 118900 | NaNs = 0
EKPC rows = 45166 | NaNs = 0
FE rows = 62706 | NaNs = 0
NI rows = 58282 | NaNs = 0
PJME rows = 145198 | NaNs = 0
PJMW rows = 143038 | NaNs = 0

In [23]:
feature_data["PJME"].head()

,Datetime,PJME_MW,hour,day,day_of_week,month,year,is_weekend,season,lag_1,lag_2,lag_3,lag_24,lag_48,lag_168,rolling_mean_24,rolling_std_24,rolling_mean_168
0,2002-01-08 01:00:00,29445.0,1,8,1,1,2002,0,Winter,31187.0,33579.0,35997.0,26862.0,27100.0,30393.0,33452.583333,4559.767709,32519.511905
1,2002-01-08 02:00:00,28670.0,2,8,1,1,2002,0,Winter,29445.0,31187.0,33579.0,25976.0,26097.0,29265.0,33560.208333,4425.965952,32513.869048
2,2002-01-08 03:00:00,28375.0,3,8,1,1,2002,0,Winter,28670.0,29445.0,31187.0,25641.0,25793.0,28357.0,33672.458333,4256.159403,32510.327381
3,2002-01-08 04:00:00,28542.0,4,8,1,1,2002,0,Winter,28375.0,28670.0,29445.0,25666.0,25657.0,27899.0,33786.375000,4064.104959,32510.434524
4,2002-01-08 05:00:00,29261.0,5,8,1,1,2002,0,Winter,28542.0,28375.0,28670.0,26328.0,25778.0,28057.0,33906.208333,3851.076461,32514.261905

In [24]:
feature_data["PJME"].dtypes

Datetime            datetime64[us]
PJME_MW                    float64
hour                         int32
day                          int32
day_of_week                  int32
month                        int32
year                         int32
is_weekend                   int64
season                         str
lag_1                      float64
lag_2                      float64
lag_3                      float64
lag_24                     float64
lag_48                     float64
lag_168                    float64
rolling_mean_24            float64
rolling_std_24             float64
rolling_mean_168           float64
dtype: object

In [25]:
FEATURE_DIR = Path("../data/processed/features")
FEATURE_DIR.mkdir(parents=True, exist_ok=True)

In [26]:
for region, df in feature_data.items():
    output_path = FEATURE_DIR / f"{region}_features.csv"
    df.to_csv(output_path, index=False)

print("All 11 feature datasets saved.")

All 11 feature datasets saved.